[project]
name = "dbt-bq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery>=1.8.3",
    "dbt-core>=1.8.8",
    "pre-commit>=4.0.1",
    "sqlfluff>=3.2.5",
]
